AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Auto Finance Application

  This template defines the resources for the Auto Finance application. It includes
  Lambda functions, API Gateway, and other necessary components.

  "
Parameters:
  ENV:
    Type: String
    Description: The environment for the stack

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Runtime: provided.al2023
    Architectures:
      - arm64
    Tags:
      AppManagerCFNStackKey: !Sub ${AWS::StackName}
      AppManagerCFNStackName: !Sub ${AWS::StackName}
    Environment:
      Variables:
        LOG_LEVEL: info

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api
      StageName: !Sub ${ENV}

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: ApiGateway
    Properties:
      Name: !Sub ${AWS::StackName}-ApiKey
      Description: !Sub API Key for Auto Finance application ${ENV}
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGateway
          StageName: !Sub ${ENV}

  ApiKeyUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiKey
    Properties:
      UsagePlanName: !Sub ${AWS::StackName}-UsagePlan
      Description: !Sub Usage plan for Auto Finance application ${ENV}
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Sub ${ENV}
      Throttle:
        BurstLimit: 10
        RateLimit: 10

  ApiKeyUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiKeyUsagePlan

  LogAutoFinanceFunctionLogGroup:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AutoFinanceFunction}
      RetentionInDays: 7

  AutoFinanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-function
      Description: !Sub Lambda function for Auto Finance application ${ENV}
      CodeUri: ../bin/auto-finance.zip
      Handler: bootstrap
      Environment:
        Variables:
          SHEET_KEY:
            Ref: SheetKey
          CONFIGURATION_BUCKET:
            Ref: ConfigurationBucket
      Policies:
        - Statement:
            - Sid: AllowSSMParameterAccess
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParametersByPath
              Resource:
                Fn::Sub: arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/af/gsheet/key
            - Sid: AllowS3BucketAccess
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:ListObjects
              Resource:
                - Fn::Sub: arn:${AWS::Partition}:s3:::${ConfigurationBucket}
                - Fn::Sub: arn:${AWS::Partition}:s3:::${ConfigurationBucket}/*
      Events:
        AutoFinance:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /finance
            Method: post
            Auth:
              ApiKeyRequired: true

  SheetKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/gsheet/key
      Type: String
      Value: TO BE FILLED
      Description: Key for access google sheet api

  AppConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${AWS::StackName}/app/config
      Type: String
      Value: TO BE FILLED
      Description: Key for access google sheet api

  ConfigurationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub config-${ENV}-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ENV}/
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ApiUrl
  ConfigurationBucketName:
    Description: Name of the S3 bucket for configuration
    Value: !Ref ConfigurationBucket
